## Deliverable 3. Create a Travel Itinerary Map.

In [23]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

In [24]:
# 1. Read the WeatherPy_vacation.csv into a DataFrame.
vacation_df = pd.read_csv("WeatherPy_vacation.csv")
vacation_df.head(20)

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,3,Boyolangu,ID,75.81,overcast clouds,-8.1181,111.8935,Yos ega cv
1,4,Tevaitoa,PF,78.35,clear sky,-16.7833,-151.5000,Hôtel Raiatea Lodge
2,10,Faanui,PF,78.55,light rain,-16.4833,-151.7500,Bora-Bora Pearl Beach Resort & Spa
3,13,Galle,LK,81.55,broken clouds,6.0367,80.2170,Amangalla
4,20,Pontianak,ID,82.38,thunderstorm,-0.0333,109.3333,Aston Pontianak Hotel & Convention Center
5,27,Davila,PH,83.91,light rain,18.4726,120.5763,Blue Ridge Beach Resort
6,28,Bengkulu,ID,80.26,broken clouds,-3.8004,102.2655,Grage Hotel Bengkulu
7,29,Hilo,US,73.80,light rain,19.7297,-155.0900,Hilo Hawaiian Hotel
8,30,Itoman,JP,82.42,few clouds,26.1247,127.6694,Southern Beach Hotel & Resort Okinawa
9,31,Belmonte,BR,79.30,clear sky,-15.8631,-38.8828,Pousada Monte Carmelo O Pão
10,32,Kahului,US,78.82,clear sky,20.8947,-156.4700,Maui Seaside Hotel
11,35,Sangmelima,CM,74.34,overcast clouds,2.9333,11.9833,gamestar hotel
12,36,Bondeno,IT,79.11,overcast clouds,44.8862,11.4108,Locanda e Cucina il Fagiano
13,39,Yumen,CN,74.70,few clouds,40.2833,97.2000,NaN
14,41,Labuhan,ID,82.72,broken clouds,-6.8844,112.2051,PT PPI Lamongan Tambak C
15,42,Xiamen,CN,80.96,clear sky,24.4798,118.0819,Xiamen Dongchen Hotel
16,45,Avarua,CK,75.25,overcast clouds,-21.2078,-159.7750,Paradise Inn
17,49,Harper,LR,80.11,light rain,4.3750,-7.7169,Screensaver
18,50,Naze,JP,77.52,scattered clouds,28.3667,129.4833,オーベルジュ・アガルイ
19,51,Codajas,BR,79.54,few clouds,-3.8367,-62.0569,Hotel Tucunaré

In [25]:
# 2. Using the template add the city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description} and {Max Temp} °F</dd>
</dl>
"""

# 3a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in vacation_df.iterrows()]

# 3b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = vacation_df[["Lat", "Lng"]]

In [26]:
# 4a. Add a marker layer for each city to the map.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.75)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)
# 4b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))

In [34]:
# From the map above pick 4 cities and create a vacation itinerary route to travel between the four cities. 
# 5. Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 
# Hint: The starting and ending city should be the same city.

vacation_start = vacation_df.loc[vacation_df['City'] == 'Freeport']
vacation_end = vacation_df.loc[vacation_df['City'] == 'Freeport']
vacation_stop1 = vacation_df.loc[vacation_df['City'] == 'Ocean City']
vacation_stop2 = vacation_df.loc[vacation_df['City'] == 'Mayo'] 
vacation_stop3 = vacation_df.loc[vacation_df['City'] == 'Virginia Beach'] 
vacation_stop1

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
296,687,Ocean City,US,74.21,overcast clouds,39.2776,-74.5746,Biscayne Suites

In [35]:
vacation_stop2

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
143,373,Mayo,US,73.81,mist,38.8876,-76.5119,Resorts Resource Group International

In [36]:
vacation_stop3

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
203,497,Virginia Beach,US,77.05,overcast clouds,36.8529,-75.978,Hilton Virginia Beach Oceanfront

In [37]:
vacation_end

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
281,656,Freeport,US,71.26,overcast clouds,40.6576,-73.5832,The Freeport Inn and Marina

In [28]:
# 6. Get the latitude-longitude pairs as tuples from each city DataFrame using the to_numpy function and list indexing.
start = vacation_start.iloc[0,5:7].to_numpy()
end = vacation_end.iloc[0,5:7].to_numpy()
stop1 = vacation_stop1.iloc[0,5:7].to_numpy()
stop2 = vacation_stop2.iloc[0,5:7].to_numpy()
stop3 = vacation_stop3.iloc[0,5:7].to_numpy()

start

array([40.6576, -73.5832], dtype=object)

In [29]:
# 7. Create a direction layer map using the start and end latitude-longitude pairs,
# and stop1, stop2, and stop3 as the waypoints. The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".

fig=gmaps.figure()
trip_stops= gmaps.directions_layer(start,end, waypoints=[stop1,stop2,stop3], travel_mode='DRIVING')
fig.add_layer(trip_stops)
fig

Figure(layout=FigureLayout(height='420px'))

In [30]:
# 8. To create a marker layer map between the four cities.
#  Combine the four city DataFrames into one DataFrame using the concat() function.
itinerary_df = pd.concat([vacation_start,vacation_stop1,vacation_stop2,vacation_stop3,vacation_end],ignore_index=True)
itinerary_df

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,656,Freeport,US,71.26,overcast clouds,40.6576,-73.5832,The Freeport Inn and Marina
1,687,Ocean City,US,74.21,overcast clouds,39.2776,-74.5746,Biscayne Suites
2,373,Mayo,US,73.81,mist,38.8876,-76.5119,Resorts Resource Group International
3,497,Virginia Beach,US,77.05,overcast clouds,36.8529,-75.9780,Hilton Virginia Beach Oceanfront
4,656,Freeport,US,71.26,overcast clouds,40.6576,-73.5832,The Freeport Inn and Marina

In [31]:
# 9 Using the template add city name, the country code, the weather description and maximum temperature for the city. 
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description} and {Max Temp} °F</dd>
</dl>
"""

# 10a Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in itinerary_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = itinerary_df[["Lat", "Lng"]]

In [22]:
# 11a. Add a marker layer for each city to the map.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.75)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)
# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))